# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='columns.Tag'),
        ),
    ]
